# theme: jekyll-theme-minimal
remote_theme: jekyll/minima
# title: home page of xxx
# markdown: kramdown

# Site Settings
locale                   : "en-US"
title                    : "Site Title"
title_separator          : "-"
name                     : "Your Name"
description              : "An amazing website."


# header_pages:
#  - research.md
#  - portfolio.md


# Reading Files
include:
  - .htaccess
  - _pages



# Conversion
markdown: kramdown
highlighter: rouge



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

compress_html:
  clippings: all
  ignore:

